// <auto-generated />
namespace POSManagementSystem.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Category_Display_Anotation_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_Display_Anotation_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201907291055060_Category_Display_Anotation_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
