// <auto-generated />
namespace POSManagementSystem.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class duplicate_category_check_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duplicate_category_check_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201907311328303_duplicate_category_check_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
